---
- hosts: ubuntu@35.177.163.180

  become: yes
  vars:
    http_port: 80
    max_clients: 500
  remote_user: root
  tasks:
    - name: Latest Apache version installed
      yum:
        name: httpd
        state: latest
    - name: Apache enabled and running
      service:
        name: httpd
        enabled: true
        state: started
